"""empty message

Revision ID: cef5d17ba075
Revises: 66d844ed50be
Create Date: 2025-11-14 01:55:16.291948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef5d17ba075'
down_revision = '66d844ed50be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planeta_personaje',
    sa.Column('planeta_id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.PrimaryKeyConstraint('planeta_id', 'personaje_id')
    )
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint('personajes_planeta_id_fkey', type_='foreignkey')
        batch_op.drop_column('planeta_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('personajes_planeta_id_fkey', 'planetas', ['planeta_id'], ['id'])

    op.drop_table('planeta_personaje')
    # ### end Alembic commands ###
